global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - /etc/prometheus/alerts/api_alerts.yml
  - /etc/prometheus/alerts/ml_alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'movie-rating-api'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
